language: java
jdk:
- oraclejdk8
notifications:
  slack:
    rooms:
      secure: F+o9FPgJxD6KnpcvCGm2VgvY72aCo/+RwBoIZoArB68L41rgiOUoKbqkH3Y1vLaqw6isyqa6dkuBKyFoKVwyjuDYn7Iaw2z86WZWRCB4SkqcAnVWQCUGZVPrFh38hUl++gUEYbzIPDLm8RgKOJr/9XBZaMoATJlmoenI9ZMuncI=
