apiendpoint:
  image: openmhealth/shimmer-api-endpoint
  environment:
    SPRING_PROFILES_ACTIVE: development
    OPENMHEALTH_SHIM_SERVER_CALLBACKURLBASE: http://192.168.99.100:8083
  links:
    - mongo:mongo

mongo:
  image: mongo

ui:
  image: openmhealth/shimmer-console
  ports:
    - "8083:8083"
  links:
    - apiendpoint:api-endpoint
