apiendpoint:
  build: shim-server/docker
  environment:
    SPRING_PROFILES_ACTIVE: development
    OPENMHEALTH_SHIM_SERVER_CALLBACKURLBASE: http://192.168.99.100:8083
  links:
    - mongo:mongo

mongo:
  image: mongo

ui:
  build: shim-server-ui/docker
  ports:
    - "8083:8083"
  links:
    - apiendpoint:api-endpoint
