spring:
  application:
    name: OMH OAuth2 Client
  data:
    mongodb:
      uri: mongodb://localhost:27017/omh_dsu
server:
  port: 8083
security:
  basic:
    enabled: false

openmhealth:
  shim:
    server:
      callbackUrlBase: http://localhost:8083
      #callbackUrlBase: http://54.88.92.112:8083
logging:
  file: hipbone-jobs.log