spring:
  application:
    name: OMH OAuth2 Client
#server:
  #port: 8081
  # use a different path for the client (otherwise cookies are shared)
  #context_path: /client
security:
  basic:
    enabled: false