spring:
  application:
    name: Open mHealth shim server
  data:
    mongodb:
      uri: mongodb://localhost:27017/omh_dsu
server:
  port: 8083
security:
  basic:
    enabled: false
logging:
  file: omh-shims.log
http:
  mappers:
    jsonPrettyPrint: true

openmhealth:
  shim:
    server:
      callbackUrlBase: http://localhost:8083
    #fitbit:
    #  clientId: YOUR_FITBIT_CLIENT_ID
    #  clientSecret: YOUR_FITBIT_SECRET
    #fatsecret:
    #  clientId: YOUR_FATSECRET_CLIENT_ID
    #  clientSecret: YOUR_FATSECRET_SECRET
    #jawbone:
    #  clientId: YOUR_JAWBONE_CLIENT_ID
    #  clientSecret: YOUR_JAWBONE_SECRET
    #runkeeper:
    #  clientId: YOUR_RUNKEEPER_CLIENT_ID
    #  clientSecret: YOUR_RUNKEEPER_SECRET
    #withings:
    #  clientId: YOUR_WITHINGS_CLIENT_ID
    #  clientSecret: YOUR_WITHINGS_SECRET
    #healthvault:
    #  clientId: YOUR_HEALTHVAULT_SECRET
